dcf_lazyload_base:
  type: mapping
  label: 'DCF Lazy Loading image base display format settings'
  mapping:
    dcf_lazyload_enable:
      type: boolean
      label: 'DCF Lazy Load enabled'
    dcf_lazyload_sizes:
      type: boolean
      label: 'DCF Lazy Loading auto-calculate sizes enabled'

field.formatter.third_party.dcf_lazyload:
  type: dcf_lazyload_base
  label: 'DCF Lazy Load image display format settings'

dcf_lazyload.settings:
  type: config_object
  label: 'DCF Lazy Loading settings'
  mapping:
    assets_source:
      type: string
      label: 'Assets Source'
