# Plugin \Drupal\dcf_ckeditor\Plugin\CKEditorPlugin\DcfBasePlugin
ckeditor.plugin.dcf_base:
  type: mapping
  label: 'DCF CKEditor Base configuration'
  mapping:
    enabled_plugins:
      type: sequence
      label: 'Enabled Plugins'
      sequence:
        type: string
        lable: 'Plugin Enabled/Disabled'
